BookSellingProject/Models/ViewModels/CartViewModel.cs
using BookSellingProject.Models.Domain;

namespace BookSellingProject.Models.ViewModels
{
    public class CartViewModel
    {
        public Guid Id { get; set; }

        public Book Book { get; set; }

        public int Quantity { get; set; }

        public int SubTotal { get; set; }

    }
}

BookSellingProject/Controllers/CartsController.cs
using BookSellingProject.Data;
using BookSellingProject.Models.Domain;
using BookSellingProject.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NToastNotify;

namespace BookSellingProject.Controllers
{

    public class CartsController : Controller
    {
        private readonly BookProjectDbContext context;
        private readonly IToastNotification toastNotification;
        private readonly IHttpContextAccessor contextAccessor;

        public CartsController(BookProjectDbContext context,
            IToastNotification toastNotification,
            IHttpContextAccessor contextAccessor)
        {
            this.context = context;
            this.toastNotification = toastNotification;
            this.contextAccessor = contextAccessor;
        }

        public async Task<IActionResult> Index()
        {

            var cartsJson = contextAccessor.HttpContext.Session.GetString("Cart");

            if (cartsJson == null && string.IsNullOrEmpty(cartsJson))
            {
                return RedirectToAction("Index", "Home");
            }

            // List<>
            var carts = JsonConvert.DeserializeObject<List<CartItem>>(cartsJson);

            var cartViewModel = new List<CartViewModel>();

            foreach(var cart in carts) {
                cartViewModel.Add(new CartViewModel
                {
                    Id = cart.Id,
                    Book = context.Books.FirstOrDefault(b => b.Id == cart.BookId),
                    Quantity = cart.Quantity,
                    SubTotal = cart.SubTotal,
                });
            }

            return View(cartViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> AddCart(Guid id)
        {
            var book = context.Books.FirstOrDefault(book => book.Id == id);

            if (book == null)
            {
                return NotFound();
            }

            var cartJSON = contextAccessor.HttpContext.Session.GetString("Cart");

            if (cartJSON == null)
            {
                cartJSON = JsonConvert.SerializeObject(new List<CartItem>());
            }


            var cartsDomain = JsonConvert.DeserializeObject<List<CartItem>>(cartJSON);

            var existingBook = cartsDomain.FirstOrDefault(cart => cart.BookId == id);
            var quantity = 1;

            if (existingBook is null)
            {
                var cartItem = new CartItem
                {
                    Id = Guid.NewGuid(),
                    Quantity = quantity,
                    SubTotal = quantity * book.Price,
                    BookId = book.Id,
                };
                cartsDomain.Add(cartItem);

                var existingCarts = JsonConvert.SerializeObject(cartsDomain);
                contextAccessor.HttpContext.Session.SetString("Cart", existingCarts);
                toastNotification.AddSuccessToastMessage("A Book is added successfully");

                return RedirectToAction("Index", "Carts");

            }

            quantity += existingBook.Quantity;

            existingBook.Quantity = quantity;
            existingBook.SubTotal *= existingBook.Quantity;

            var carts = JsonConvert.SerializeObject(cartsDomain);
            contextAccessor.HttpContext.Session.SetString("Cart", carts);


            return RedirectToAction("Index", "Carts");
        }


        public async Task<IActionResult> Delete(Guid id)
        {

            var cartJSON = contextAccessor.HttpContext.Session.GetString("Cart");


            var cartsDomain = JsonConvert.DeserializeObject<List<CartItem>>(cartJSON);

            foreach (var cart in cartsDomain)
            {
                if (cart.Id == id)
                {
                    cartsDomain.Remove(cart);
                    break;
                }
            }

            var existingCarts = JsonConvert.SerializeObject(cartsDomain);
            contextAccessor.HttpContext.Session.SetString("Cart", existingCarts);
            toastNotification.AddSuccessToastMessage("A Book is deleted successfully");

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(Guid Id, int Quantity)
        {
            var cartJSON = contextAccessor.HttpContext.Session.GetString("Cart");


            if (cartJSON != null)
            {

                var cartsDomain = JsonConvert.DeserializeObject<List<CartItem>>(cartJSON);
                int subTotal = 0;

                // Id san pham = so luong hien tai
                foreach (var cart in cartsDomain)
                {
                    if (cart.Id == Id)
                    {
                        cart.Quantity = Quantity;
                        var book = context.Books.FirstOrDefault(x => x.Id == cart.BookId);
                        if (book != null)
                        {
                            cart.SubTotal = cart.Quantity * book.Price;
                            subTotal = cart.SubTotal;
                        }
                    }
                }
                // Cap nhat
                var existingCarts = JsonConvert.SerializeObject(cartsDomain);
                contextAccessor.HttpContext.Session.SetString("Cart", existingCarts);

                return Ok(new
                {
                    SubTotal = subTotal,
                    Total = cartsDomain.Sum(c => c.SubTotal)
                });
            }

            return RedirectToAction("Index", "Carts");

        }
    }
}

BookSellingProject/Controllers/CheckoutController.cs
using BookSellingProject.Data;
using BookSellingProject.Models.Domain;
using BookSellingProject.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NToastNotify;

namespace BookSellingProject.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly BookProjectDbContext context;
        private readonly IToastNotification toastNotification;
        private readonly IHttpContextAccessor contextAccessor;
        private readonly BookProjectDbContext bookProjectDbContext;

        public CheckoutController(BookProjectDbContext context,
            IToastNotification toastNotification,
            IHttpContextAccessor contextAccessor, 
            BookProjectDbContext bookProjectDbContext)
        {
            this.context = context;
            this.toastNotification = toastNotification;
            this.contextAccessor = contextAccessor;
            this.bookProjectDbContext = bookProjectDbContext;
        }

        public IActionResult Index()
        {
            var cartsJson = contextAccessor.HttpContext.Session.GetString("Cart");

            if (cartsJson == null && string.IsNullOrEmpty(cartsJson))
            {
                return RedirectToAction("Index", "Home");
            }

            // List<>
            var carts = JsonConvert.DeserializeObject<List<CartItem>>(cartsJson);

            var cartViewModel = new List<CartViewModel>();

            foreach (var cart in carts)
            {
                cartViewModel.Add(new CartViewModel
                {
                    Id = cart.Id,
                    Book = context.Books.FirstOrDefault(b => b.Id == cart.BookId),
                    Quantity = cart.Quantity,
                    SubTotal = cart.SubTotal,
                });
            }

            var checkoutViewModel = new CreateCheckoutViewModel
            {
                CartItem = cartViewModel
            };

            return View(checkoutViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Submit(CreateCheckoutViewModel createCheckoutViewModel)
        {
            var cartsJson = contextAccessor.HttpContext.Session.GetString("Cart");

            if (cartsJson == null && string.IsNullOrEmpty(cartsJson))
            {
                return RedirectToAction("Index", "Home");
            }

            var carts = JsonConvert.DeserializeObject<List<CartItem>>(cartsJson);


            var checkoutDomain = new Invoice
            {
                Id = Guid.NewGuid(),
                Name = createCheckoutViewModel.Name,
                Address = createCheckoutViewModel.Address,
                Email = createCheckoutViewModel.Email,
                Telephone = createCheckoutViewModel.Telephone,
                Note = createCheckoutViewModel.Note,
                Total = createCheckoutViewModel.Total,
                CartItems = carts,
                CreatedAt = DateTime.Now,
            };

            await bookProjectDbContext.Invoices.AddAsync(checkoutDomain);
            
            await bookProjectDbContext.SaveChangesAsync();
            toastNotification.AddSuccessToastMessage("Thank you for your order! Your order is created successfully");

            contextAccessor.HttpContext.Session.SetString("Cart", "");
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> List()
        {
            var invoices = await context.Invoices
                .OrderByDescending(i => i.CreatedAt)
                .ToListAsync();

            return View(invoices);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Detail(Guid id)
        {
            var invoice = await context.Invoices.
                Include(i => i.CartItems)
                .FirstOrDefaultAsync(i => i.Id == id);

            var cartViewModel = new List<CartViewModel>();

            foreach (var cart in invoice.CartItems)
            {
                cartViewModel.Add(new CartViewModel
                {
                    Id = cart.Id,
                    Book = context.Books.FirstOrDefault(b => b.Id == cart.BookId),
                    Quantity = cart.Quantity,
                    SubTotal = cart.SubTotal,
                });
            }

            var invoiceViewModel = new InvoiceViewModel
            {
                Id = invoice.Id,
                Name = invoice.Name,
                Address = invoice.Address,
                CreatedAt = invoice.CreatedAt,
                Email = invoice.Email,
                Note = invoice.Note,
                Telephone = invoice.Telephone,
                Total = invoice.Total,
                CartItems = cartViewModel
            };

            if (invoice == null)
                return View("Error");


            return View(invoiceViewModel);
        }
    }
}

BookSellingProject/Views/Carts/Index.cshtml
@model List<BookSellingProject.Models.ViewModels.CartViewModel>

@{
    ViewData["Title"] = "Cart";
}
<!-- breadcrumb -->
<div class="container">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
        <a asp-controller="Home" asp-action="Index" class="stext-109 cl8 hov-cl1 trans-04">
            Home
            <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
        </a>

        <span class="stext-109 cl4">
            Shopping Cart
        </span>
    </div>
</div>

<!-- Shoping Cart -->
<form class="bg0 p-t-75 p-b-85">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
                <div class="m-l-25 m-r--38 m-lr-0-xl">
                    <div class="wrap-table-shopping-cart">

                        @if (Model is not null && Model.Any())
                        {
                            <form asp-action="Update" asp-controller="Carts" method="post">
                                <table class="table-shopping-cart">
                                    <tr class="table_head">
                                        <th class="column-1">Image</th>
                                        <th class="column-2">Name</th>
                                        <th class="column-3">Price</th>
                                        <th class="column">Quantity</th>
                                        <th class="column-5">Sub-total</th>
                                        <th class="column-6">Operation</th>
                                    </tr>
                                    @foreach (var item in Model)
                                    {
                                        <tr class="table_row">
                                            <td class="column-1">
                                                <div class="how-itemcart1">
                                                    <img src="@item.Book.Image" alt="IMG">
                                                </div>
                                            </td>
                                            <td class="column-2">@item.Book.Name</td>
                                            <td class="column-3">@item.Book.Price VND</td>
                                            <td class="column-4">
                                                <input type="text" hidden readonly name="Id" value="@item.Id">
                                                <input class="num-order mtext-104 txt-center bg-light" style="width: 80px;" min="1" type="number" name="@item.Id" value="@item.Quantity">
                                            </td>

                                            <td class="column-5" id="sub_total-@item.Id">@item.SubTotal VND</td>
                                            <td class="column-6"><a class="btn btn-danger" asp-controller="Carts" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>
                                        </tr>
                                    }
                                </table>
                            </form>
                        }
                        else
                        {
                            <p>There is no items in your Cart!</p>
                        }


                    </div>

                    <div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
                        <div class="flex-w flex-m m-r-20 m-tb-5">
                            <input class="stext-104 cl2 plh4 size-117 bor13 p-lr-20 m-r-10 m-tb-5" type="text" name="coupon" placeholder="Coupon Code">

                            <div class="flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-5">
                                Apply coupon
                            </div>
                        </div>

                        <div class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">
                            Delete Cart
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
                <div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
                    <h4 class="mtext-109 cl2 p-b-30">
                        Cart Totals
                    </h4>

                    <div class="flex-w flex-t p-t-27 p-b-33">
                        <div class="size-208">
                            <span class="mtext-101 cl2">
                                Total:
                            </span>
                        </div>

                        <div class="size-209 p-t-1">
                            <span class="mtext-110 cl2" id="total">
                                @{
                                    var sum = 0;

                                    if (Model is not null)
                                    {
                                        sum = @Model.Sum(cart => cart.SubTotal);
                                    }
                                }
                                @sum VND
                            </span>
                        </div>
                    </div>

                    <a asp-controller="Checkout" asp-action="Index" class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">
                        Proceed to Checkout
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $(".num-order").change(function () {

            let id = $(this).attr('name');

            let quantity = $(this).val();

            let data = {
                Id: id,
                Quantity: quantity,
            };

            console.log(data);

            $.ajax({
                url: "https://localhost:7088/Carts/Update",
                method: 'POST',
                data: data,
                dataType: 'json',
                success: function (data) {
                    $("#sub_total-" + id).text(data.subTotal + 'VND');
                    $('#total').text(data.total + 'VND');
                },
            });
        })

    </script>
}